### ISSUE TITLE
Extract Frequency Domain 

### ISSUE THREAD

**Issue by dragonprevost** [avesk/echo-synth#4]
Given a signal return the top (10?) frequencies that are present in the signal. Make sure these frequencies are percievable by the human ear and regular hardware(within 40hz-4Khz maybe?)

#### Input: 
* Signal - array of signal data points

#### Output:
* List of most relevant frequencies in the signal with an amplitude

``` python
output = [(440, 0.8), (250, 0.3), (200, 0.1) ... ]
```

**Comment by Gohsato** [comment]
Merged with this pr: https://github.com/avesk/echo-synth/pull/13
